
#PBS -q debug
#PBS -A hacc
#PBS -l nodes=2:ppn=8
#PBS -l walltime=00:15:00
#PBS -N xi
#PBS -e xi.$PBS_JOBID.err
#PBS -o xi.$PBS.JOBID.out
#PBS -V
    
module unload pgi
module load gcc
module load fftw
module load gsl   
 
cd /project/projectdirs/hacc/PDACS/JK_Tools/

    
mpirun -np 16 /project/projectdirs/hacc/PDACS/JK_Tools/xi.out 128 /project/projectdirs/hacc/PDACS/Coyote/Grid/M001/L180/G001/snapshot_011 8.0 /project/projectdirs/hacc/PDACS/working/PS.tmp 107.586 0.0 -0.816 0.4307964

